### ISSUE TITLE
Edge case where RenamePrivateFieldsToCamelCase does not change a variable name

### ISSUE THREAD

**Issue by jbessels** [openrewrite/rewrite-static-analysis#12] opened 2023-03-14 01:52 UTC
I had almost cleaned a repo. Only one camelCasing issue remained in one file. Moved a variable in a test which was in Screaming Snake case to the top and made it a constant to prevent it was lower camelCased  eacht time by RenameLocalVariablesToCamelCase.

Hence local var 'final int NR_OF_PATH_ELEMENTS' SHOULD become 'private **static int** final NR_OF_PATH_ELEMENTS'.  BUT I forgot to add the  **static**. Hence after running recipes it was lower camel Cased again. After adding the static all was fine and nothing changed.
NOTE instead of  NR_OF_PATH_ELEMENTS it was renamed to NR_OF_PATH_ELEMENTS_NULL with a different value cause otherwise a test broke.

BUT at that moment I noticed something. Originally the code was
```
private static final String ENCODED_PATH_EMPTY = "";
private final int NR_OF_PATH_ELEMENTS = 17; <-- notice no static AND its the last line after a few constants
```

This means that this should have camelcased before!!!  ONLY after adding the new constant below it, it was picked up. BUT also ONLY after the constant was also really used in the code!! When not used it was removed by a some 'remove unused var' recipe.

Using 4.41.1 and 1.17.2. Also tested with 1.18 SNAPSHOT.

**Please the above carefully cause the devil IS in the details.**

**Comment by jbessels** [comment] 2023-05-03 15:44
**Koppor, thanks a lot.** Nice to see you have found a similar example which fits my description in the OP. 
As in: '<-- notice no static AND its the last line after a few constants'

**Comment by koppor** [comment] 2023-06-12 22:47
Following variable also was not changed:

```
        String NonUTF8 = new String("你好，这条语句使用GBK字符集".getBytes(StandardCharsets.UTF_8), GBK);
            assertFalse(UTF8Checker.UTF8EncodingChecker(NonUTF8.getBytes(GBK)));
```

**Comment by koppor** [comment] 2023-06-12 22:49
Can the renaming be more intelligent?

Actual:

```diff
-      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
+      PdfDocumentViewModel pDFviewModel = new PdfDocumentViewModel(mockPDF);
```

Expected

```diff
-      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
+      PdfDocumentViewModel pdfViewModel = new PdfDocumentViewModel(mockPDF);
```

**Comment by timtebeek** [comment] 2023-06-13 07:21
> Can the renaming be more intelligent?
> 
> Actual:
> 
> ```diff
> -      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
> +      PdfDocumentViewModel pDFviewModel = new PdfDocumentViewModel(mockPDF);
> ```
> 
> Expected
> 
> ```diff
> -      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
> +      PdfDocumentViewModel pdfViewModel = new PdfDocumentViewModel(mockPDF);
> ```

That indeed looks cleaner in your second example. The associated logic is in the original openrewrite/rewrite repository [NameCaseConvention](https://github.com/openrewrite/rewrite/blob/4a06975d4f47a63796a380e817eb68e41acf3145/rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java#L142-L149), and if updated there should cascade here. Probably best tackled in a separate issue or pull request, which could start with capturing the above in a [unit test for NameCaseConvention](https://github.com/openrewrite/rewrite/blob/4a06975d4f47a63796a380e817eb68e41acf3145/rewrite-core/src/test/java/org/openrewrite/internal/NameCaseConventionTest.java#L67-L87).

**Comment by joanvr** [comment] 2023-08-17 14:17
After reviewing this scenario, for the example provided by @koppor it seems that the issue is not related to being the last element in a sequence of variable declarations. At least in this scenario it was related to having another variable defined in the scope of the class with the same naming as the resulting new camel case name here: https://github.com/JabRef/jabref/blob/5bc359fa5f572c40ac3f05551e5eecd8126845d8/src/main/java/org/jabref/logic/importer/fileformat/CoinsParser.java#L65

Thus, the recipe is not changing this variable to avoid a potential collision and changing the behavior of the code or producing non-compilable code.

**Comment by timtebeek** [comment] 2023-11-21 13:07
Very likely since resolved in
- https://github.com/openrewrite/rewrite-static-analysis/pull/196

We can reopen if the problem persists.

**Closed by timtebeek** 2023-11-21 13:07 UTC
Labels: bug, question
